/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.vmt.gh.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Handle service. Represents a row in the &quot;gh_Handle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.vmt.gh.sb.model.impl.HandleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.vmt.gh.sb.model.impl.HandleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Handle
 * @generated
 */
@ProviderType
public interface HandleModel
	extends BaseModel<Handle>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a handle model instance should use the {@link Handle} interface instead.
	 */

	/**
	 * Returns the primary key of this handle.
	 *
	 * @return the primary key of this handle
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this handle.
	 *
	 * @param primaryKey the primary key of this handle
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this handle.
	 *
	 * @return the uuid of this handle
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this handle.
	 *
	 * @param uuid the uuid of this handle
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the handle ID of this handle.
	 *
	 * @return the handle ID of this handle
	 */
	public long getHandleId();

	/**
	 * Sets the handle ID of this handle.
	 *
	 * @param handleId the handle ID of this handle
	 */
	public void setHandleId(long handleId);

	/**
	 * Returns the group ID of this handle.
	 *
	 * @return the group ID of this handle
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this handle.
	 *
	 * @param groupId the group ID of this handle
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this handle.
	 *
	 * @return the company ID of this handle
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this handle.
	 *
	 * @param companyId the company ID of this handle
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this handle.
	 *
	 * @return the user ID of this handle
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this handle.
	 *
	 * @param userId the user ID of this handle
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this handle.
	 *
	 * @return the user uuid of this handle
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this handle.
	 *
	 * @param userUuid the user uuid of this handle
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this handle.
	 *
	 * @return the user name of this handle
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this handle.
	 *
	 * @param userName the user name of this handle
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this handle.
	 *
	 * @return the create date of this handle
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this handle.
	 *
	 * @param createDate the create date of this handle
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this handle.
	 *
	 * @return the modified date of this handle
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this handle.
	 *
	 * @param modifiedDate the modified date of this handle
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this handle.
	 *
	 * @return the code of this handle
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this handle.
	 *
	 * @param code the code of this handle
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this handle.
	 *
	 * @return the name of this handle
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this handle.
	 *
	 * @param name the name of this handle
	 */
	public void setName(String name);

	/**
	 * Returns the price of this handle.
	 *
	 * @return the price of this handle
	 */
	public double getPrice();

	/**
	 * Sets the price of this handle.
	 *
	 * @param price the price of this handle
	 */
	public void setPrice(double price);

	/**
	 * Returns the img of this handle.
	 *
	 * @return the img of this handle
	 */
	@AutoEscape
	public String getImg();

	/**
	 * Sets the img of this handle.
	 *
	 * @param img the img of this handle
	 */
	public void setImg(String img);

}