/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.vmt.gh.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import it.vmt.gh.sb.service.persistence.Profile_CarpentryPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Profile_Carpentry service. Represents a row in the &quot;gh_Profile_Carpentry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.vmt.gh.sb.model.impl.Profile_CarpentryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.vmt.gh.sb.model.impl.Profile_CarpentryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Profile_Carpentry
 * @generated
 */
@ProviderType
public interface Profile_CarpentryModel extends BaseModel<Profile_Carpentry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile_ carpentry model instance should use the {@link Profile_Carpentry} interface instead.
	 */

	/**
	 * Returns the primary key of this profile_ carpentry.
	 *
	 * @return the primary key of this profile_ carpentry
	 */
	public Profile_CarpentryPK getPrimaryKey();

	/**
	 * Sets the primary key of this profile_ carpentry.
	 *
	 * @param primaryKey the primary key of this profile_ carpentry
	 */
	public void setPrimaryKey(Profile_CarpentryPK primaryKey);

	/**
	 * Returns the uuid of this profile_ carpentry.
	 *
	 * @return the uuid of this profile_ carpentry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this profile_ carpentry.
	 *
	 * @param uuid the uuid of this profile_ carpentry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the profile ID of this profile_ carpentry.
	 *
	 * @return the profile ID of this profile_ carpentry
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this profile_ carpentry.
	 *
	 * @param profileId the profile ID of this profile_ carpentry
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the carpentry ID of this profile_ carpentry.
	 *
	 * @return the carpentry ID of this profile_ carpentry
	 */
	public long getCarpentryId();

	/**
	 * Sets the carpentry ID of this profile_ carpentry.
	 *
	 * @param carpentryId the carpentry ID of this profile_ carpentry
	 */
	public void setCarpentryId(long carpentryId);

}