/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.vmt.gh.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Profile service. Represents a row in the &quot;gh_Profile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.vmt.gh.sb.model.impl.ProfileModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.vmt.gh.sb.model.impl.ProfileImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Profile
 * @generated
 */
@ProviderType
public interface ProfileModel
	extends BaseModel<Profile>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile model instance should use the {@link Profile} interface instead.
	 */

	/**
	 * Returns the primary key of this profile.
	 *
	 * @return the primary key of this profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile.
	 *
	 * @param primaryKey the primary key of this profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this profile.
	 *
	 * @return the uuid of this profile
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this profile.
	 *
	 * @param uuid the uuid of this profile
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the profile ID of this profile.
	 *
	 * @return the profile ID of this profile
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this profile.
	 *
	 * @param profileId the profile ID of this profile
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the group ID of this profile.
	 *
	 * @return the group ID of this profile
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this profile.
	 *
	 * @param groupId the group ID of this profile
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this profile.
	 *
	 * @return the company ID of this profile
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this profile.
	 *
	 * @param companyId the company ID of this profile
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this profile.
	 *
	 * @return the user ID of this profile
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this profile.
	 *
	 * @param userId the user ID of this profile
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this profile.
	 *
	 * @return the user uuid of this profile
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this profile.
	 *
	 * @param userUuid the user uuid of this profile
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this profile.
	 *
	 * @return the user name of this profile
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this profile.
	 *
	 * @param userName the user name of this profile
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this profile.
	 *
	 * @return the create date of this profile
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this profile.
	 *
	 * @param createDate the create date of this profile
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this profile.
	 *
	 * @return the modified date of this profile
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this profile.
	 *
	 * @param modifiedDate the modified date of this profile
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this profile.
	 *
	 * @return the code of this profile
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this profile.
	 *
	 * @param code the code of this profile
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this profile.
	 *
	 * @return the name of this profile
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this profile.
	 *
	 * @param name the name of this profile
	 */
	public void setName(String name);

	/**
	 * Returns the price of this profile.
	 *
	 * @return the price of this profile
	 */
	public double getPrice();

	/**
	 * Sets the price of this profile.
	 *
	 * @param price the price of this profile
	 */
	public void setPrice(double price);

	/**
	 * Returns the img of this profile.
	 *
	 * @return the img of this profile
	 */
	@AutoEscape
	public String getImg();

	/**
	 * Sets the img of this profile.
	 *
	 * @param img the img of this profile
	 */
	public void setImg(String img);

}