/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.vmt.gh.sb.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import it.vmt.gh.sb.model.Profile_Carpentry;
import it.vmt.gh.sb.model.Profile_CarpentryModel;
import it.vmt.gh.sb.model.Profile_CarpentrySoap;
import it.vmt.gh.sb.service.persistence.Profile_CarpentryPK;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Profile_Carpentry service. Represents a row in the &quot;gh_Profile_Carpentry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Profile_CarpentryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Profile_CarpentryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Profile_CarpentryImpl
 * @generated
 */
@JSON(strict = true)
public class Profile_CarpentryModelImpl
	extends BaseModelImpl<Profile_Carpentry> implements Profile_CarpentryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a profile_ carpentry model instance should use the <code>Profile_Carpentry</code> interface instead.
	 */
	public static final String TABLE_NAME = "gh_Profile_Carpentry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"profileId", Types.BIGINT},
		{"carpentryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("profileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("carpentryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table gh_Profile_Carpentry (uuid_ VARCHAR(75) null,profileId LONG not null,carpentryId LONG not null,primary key (profileId, carpentryId))";

	public static final String TABLE_SQL_DROP =
		"drop table gh_Profile_Carpentry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY profile_Carpentry.id.profileId ASC, profile_Carpentry.id.carpentryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY gh_Profile_Carpentry.profileId ASC, gh_Profile_Carpentry.carpentryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CARPENTRYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PROFILEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Profile_Carpentry toModel(Profile_CarpentrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Profile_Carpentry model = new Profile_CarpentryImpl();

		model.setUuid(soapModel.getUuid());
		model.setProfileId(soapModel.getProfileId());
		model.setCarpentryId(soapModel.getCarpentryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Profile_Carpentry> toModels(
		Profile_CarpentrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<Profile_Carpentry> models = new ArrayList<Profile_Carpentry>(
			soapModels.length);

		for (Profile_CarpentrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public Profile_CarpentryModelImpl() {
	}

	@Override
	public Profile_CarpentryPK getPrimaryKey() {
		return new Profile_CarpentryPK(_profileId, _carpentryId);
	}

	@Override
	public void setPrimaryKey(Profile_CarpentryPK primaryKey) {
		setProfileId(primaryKey.profileId);
		setCarpentryId(primaryKey.carpentryId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new Profile_CarpentryPK(_profileId, _carpentryId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((Profile_CarpentryPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Profile_Carpentry.class;
	}

	@Override
	public String getModelClassName() {
		return Profile_Carpentry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Profile_Carpentry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Profile_Carpentry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Profile_Carpentry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Profile_Carpentry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Profile_Carpentry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Profile_Carpentry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Profile_Carpentry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Profile_Carpentry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Profile_Carpentry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Profile_Carpentry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Profile_Carpentry.class.getClassLoader(), Profile_Carpentry.class,
			ModelWrapper.class);

		try {
			Constructor<Profile_Carpentry> constructor =
				(Constructor<Profile_Carpentry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Profile_Carpentry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Profile_Carpentry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Profile_Carpentry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<Profile_Carpentry, Object>>();
		Map<String, BiConsumer<Profile_Carpentry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Profile_Carpentry, ?>>();

		attributeGetterFunctions.put("uuid", Profile_Carpentry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<Profile_Carpentry, String>)Profile_Carpentry::setUuid);
		attributeGetterFunctions.put(
			"profileId", Profile_Carpentry::getProfileId);
		attributeSetterBiConsumers.put(
			"profileId",
			(BiConsumer<Profile_Carpentry, Long>)
				Profile_Carpentry::setProfileId);
		attributeGetterFunctions.put(
			"carpentryId", Profile_Carpentry::getCarpentryId);
		attributeSetterBiConsumers.put(
			"carpentryId",
			(BiConsumer<Profile_Carpentry, Long>)
				Profile_Carpentry::setCarpentryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProfileId() {
		return _profileId;
	}

	@Override
	public void setProfileId(long profileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_profileId = profileId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProfileId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("profileId"));
	}

	@JSON
	@Override
	public long getCarpentryId() {
		return _carpentryId;
	}

	@Override
	public void setCarpentryId(long carpentryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_carpentryId = carpentryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCarpentryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("carpentryId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Profile_Carpentry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Profile_Carpentry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Profile_CarpentryImpl profile_CarpentryImpl =
			new Profile_CarpentryImpl();

		profile_CarpentryImpl.setUuid(getUuid());
		profile_CarpentryImpl.setProfileId(getProfileId());
		profile_CarpentryImpl.setCarpentryId(getCarpentryId());

		profile_CarpentryImpl.resetOriginalValues();

		return profile_CarpentryImpl;
	}

	@Override
	public int compareTo(Profile_Carpentry profile_Carpentry) {
		Profile_CarpentryPK primaryKey = profile_Carpentry.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Profile_Carpentry)) {
			return false;
		}

		Profile_Carpentry profile_Carpentry = (Profile_Carpentry)object;

		Profile_CarpentryPK primaryKey = profile_Carpentry.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Profile_Carpentry> toCacheModel() {
		Profile_CarpentryCacheModel profile_CarpentryCacheModel =
			new Profile_CarpentryCacheModel();

		profile_CarpentryCacheModel.profile_CarpentryPK = getPrimaryKey();

		profile_CarpentryCacheModel.uuid = getUuid();

		String uuid = profile_CarpentryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			profile_CarpentryCacheModel.uuid = null;
		}

		profile_CarpentryCacheModel.profileId = getProfileId();

		profile_CarpentryCacheModel.carpentryId = getCarpentryId();

		return profile_CarpentryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Profile_Carpentry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Profile_Carpentry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Profile_Carpentry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Profile_Carpentry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Profile_Carpentry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Profile_Carpentry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Profile_Carpentry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Profile_Carpentry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Profile_Carpentry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _profileId;
	private long _carpentryId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Profile_Carpentry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Profile_Carpentry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("profileId", _profileId);
		_columnOriginalValues.put("carpentryId", _carpentryId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("profileId", 2L);

		columnBitmasks.put("carpentryId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Profile_Carpentry _escapedModel;

}